In [2]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5', compile=False)
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

[[0.15009479 0.8286462  0.01109182 0.01016725]]
1/1 [==============================] - 0s 38ms/step
[[0.03402835 0.9573962  0.00422124 0.00435414]]
1/1 [==============================] - 0s 41ms/step
[[0.0312148  0.9619268  0.00174488 0.00511348]]
1/1 [==============================] - 0s 84ms/step
[[1.1885724e-02 9.8448390e-01 7.4958213e-04 2.8807719e-03]]
1/1 [==============================] - 0s 30ms/step
[[2.4574045e-02 9.7378790e-01 2.2502702e-04 1.4130543e-03]]
1/1 [==============================] - 0s 37ms/step
[[0.8426695  0.13244078 0.00854168 0.01634806]]
1/1 [==============================] - 0s 36ms/step
[[0.45925155 0.53401405 0.00176349 0.00497085]]
1/1 [==============================] - 0s 37ms/step
[[0.08348002 0.9118295  0.00169232 0.00299812]]
1/1 [==============================] - 0s 30ms/step
[[0.30227745 0.68380654 0.00367525 0.01024071]]
1/1 [==============================] - 0s 34ms/step
[[0.48320955 0.50700927 0.00752312 0.00225805]]
1/1 [=======================