In [14]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5', compile=False)
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

model_dic = {0:'Scissors', 1:'Rock',2: 'Paper', 3: 'Nothing'}

def get_prediction(prediction):
   indices = np.argmax(prediction[0])
   user = model_dic[indices]
   return user

get_prediction(prediction)


1/1 [==============================] - 1s 650ms/step
[[3.3825368e-02 7.0291274e-04 7.9349351e-01 1.7197821e-01]]
1/1 [==============================] - 0s 35ms/step
[[2.3223133e-07 8.3169252e-02 9.1627675e-01 5.5381900e-04]]
1/1 [==============================] - 0s 38ms/step
[[3.0535546e-06 1.9867009e-01 7.9916286e-01 2.1639704e-03]]
1/1 [==============================] - 0s 33ms/step
[[9.0821213e-06 1.6641119e-02 9.8159629e-01 1.7534117e-03]]
1/1 [==============================] - 0s 40ms/step
[[1.9434960e-05 1.6908454e-02 9.8075944e-01 2.3126649e-03]]
1/1 [==============================] - 0s 34ms/step
[[1.0104776e-06 1.1202370e-02 9.8842561e-01 3.7094162e-04]]
1/1 [==============================] - 0s 31ms/step
[[1.5116171e-06 8.1335157e-03 9.9152631e-01 3.3868098e-04]]
1/1 [==============================] - 0s 34ms/step
[[1.4992182e-06 2.0431405e-01 7.9455030e-01 1.1341133e-03]]
1/1 [==============================] - 0s 43ms/step
[[1.8189186e-06 6.3615628e-02 9.3562710e-01 7.55495

'Paper'